### ISSUE TITLE
Update to Dart 2.0.0?

### ISSUE THREAD

**Issue by 333333h1t** [semolex/ed25519_dart#1]
when I try to use it I get this error: 
```
package: ed25519_dart / src / ed25519_dart_base.dart': error: line 16 pos 1: integer literal 15112221349535400772501151409588531511454012693041857206046113283949847762202 is out of range
15112221349535400772501151409588531211454012693041857206046113283949847762202;
```
I think it is because I am using dart 2.0.0, try to change all the int to BigInt and other things but it did not work for me, I am new using dart.

**Comment by semolex** [comment]
Hey, thanks. I will take a look.

**Comment by semolex** [comment]
Hi, current version of library is not supporting 2.0, however it is open for patches, you can add one and create PR, thanks.
