### ISSUE TITLE
ed25519_dart isn't compatible with dart 2

### ISSUE THREAD

**Issue by egemenvardar** [semolex/ed25519_dart#2]
I tried using ed25519_dart in my Flutter project, but the app doesn't even start due to this error (which is also pointed out by the dart analyzer):
`integer literal can't be represented in 64 bits`

I suspect that this library isn't compatible with dart 2. Is there any plan to update it?

**Comment by semolex** [comment]
Hi, what version of Dart do you use?

**Comment by semolex** [comment]
Actual version is not optimized for Dart2
`environment:
  sdk: '>=1.20.1 <2.0.0'`

I did not used Dart2 at all, but I can check it at home, maybe I will determine solution

**Comment by egemenvardar** [comment]
I am using Flutter version 0.5.1, which uses Dart 2.0.0-dev.58.0.

Thanks - it would be great to have the dart 2 support.

**Comment by semolex** [comment]
I will try my best to implement compatibility!

**Comment by semolex** [comment]
I checked - it is not worked for me after conversion either, so need some time to see what changed in Dart2

**Comment by egemenvardar** [comment]
Thanks for looking into it. I assume `BigInt` should be used for those integers now (not sure if there are more breaking changes though). From dart 2 change log:

> BigInt class added to support integers greater than 64-bits.

**Comment by semolex** [comment]
I tried to make conversions, but BigInt is failing to use constant values.
New Dart2 is pretty bullshit thing, there is also dependencies on crypto libraries that cannot be ised in Dart2.

**Comment by egemenvardar** [comment]
As far as I've seen all crypto related libraries had a problem with dart 2. It seems that pointycastle is now compatible with dart 2 (but unfortunately they don't yet support the use case I need).

**Comment by rashedmyt** [comment]
@semolex Any updates regarding dart 2 support.. since its been a while dart 2 has been around and most other libraries have got around this issue, I was wondering if that can be done to this library too

**Comment by semolex** [comment]
@rashedmyt Unfortunately, I dropped this, while Dart2 has issues with BigNum...You might want to make a fork

**Comment by rashedmyt** [comment]
TBH I'm not a fan of python implementation.. But I'm trying to port the Go implementation of ref10.. I'm very near to complete the bare basic language port but I'm not sure if it works as expected.. would appreciate any help to make it work

**Comment by semolex** [comment]
@rashedmyt No worries, you can add me to your repo and we can try to make it together

**Comment by rashedmyt** [comment]
Sure.. haven't created the repo yet.. will add you as soon as it is up

**Comment by semolex** [comment]
Great!
